# ASMuvera Configuration

# Vespa settings
vespa:
  endpoint: "http://localhost:8080"
  document_api: "http://localhost:8080/document/v1"
  search_api: "http://localhost:8080/search/"

# Dataset settings
datasets:
  msmarco:
    passages_url: "https://rgw.cs.uwaterloo.ca/JIMMYLIN-bucket0/data/collectionandqueries.tar.gz"
    queries_url: "https://rgw.cs.uwaterloo.ca/JIMMYLIN-bucket0/data/queries.dev.small.tsv"
    qrels_url: "https://rgw.cs.uwaterloo.ca/JIMMYLIN-bucket0/data/qrels.dev.small.tsv"
    max_passages: 100000  # Set to -1 for full dataset
    
# Embedding models
models:
  single_vector:
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    dimension: 384
    
  multi_vector:
    model_name: "sentence-transformers/all-MiniLM-L6-v2"  # Fallback model
    dimension: 128
    max_tokens: 512

# Evaluation settings
evaluation:
  metrics: ["ndcg_cut_10", "map", "recip_rank", "recall_100", "recall_1000"]
  query_batch_size: 32
  top_k: 1000